In [1]:
from mmj_functions import *

In [2]:
def cal_mmj_matrix_algo_1_python_dis_matrix(distance_matrix):
 
    N = len(distance_matrix)
   
    mmj_matrix = np.zeros((N,N))

    mmj_matrix[0,1] = distance_matrix[0,1]
    mmj_matrix[1,0] = distance_matrix[1,0]
 
    for kk in range(2,N):
        cal_n_mmj(distance_matrix, mmj_matrix, kk)
    return mmj_matrix

In [3]:
def cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(distance_matrix):
    n = len(distance_matrix)    
    p = distance_matrix.copy()
 
    for i in range(n):
        for j in range(n):
            if i != j:
                for k in range(n):
                    if i != k and j != k:
                        p[j,k] = min (p[j,k], max (p[j,i], p[i,k])) 
    return p

In [4]:
import numpy as np
import random

# create distance matrix of a directed graph

def create_distance_matrix(edges, num_nodes):
 
    dist_matrix = np.full((num_nodes, num_nodes), np.inf)
 
    np.fill_diagonal(dist_matrix, 0)
 
    for u, v, w in edges:
        dist_matrix[u, v] = w
    
    return dist_matrix

 
num_nodes = 100

edges = []
for _ in range(50000):  
    u = random.randint(0, num_nodes - 1)
    v = random.randint(0, num_nodes - 1)
    if u != v:
        w = int(random.uniform(1, 1000))
        edges.append((u, v, w))
 
distance_matrix = create_distance_matrix(edges, num_nodes)

print(distance_matrix[:10, :10])  


[[  0. 424. 160. 275. 199. 523. 260. 156. 926. 439.]
 [218.   0. 193. 837. 798.  39. 867. 959. 992. 852.]
 [195. 281.   0. 928. 759. 456. 162. 218. 812. 694.]
 [953. 870. 992.   0. 281. 981.  44. 391. 335. 904.]
 [ 58. 386. 372. 420.   0. 806. 602. 664. 911. 971.]
 [823. 384. 913. 389.  72.   0. 365. 562. 205. 649.]
 [835. 568. 843. 567.  44. 176.   0.   8. 377. 933.]
 [394. 965. 684. 800. 234. 276.  78.   0. 546. 396.]
 [924. 105. 256.   6. 750. 516. 233. 842.   0. 483.]
 [786. 835. 180. 363.  75. 895. 148. 197. 128.   0.]]


In [5]:

X_mmj_matrix_python_algo_1 = cal_mmj_matrix_algo_1_python_dis_matrix(distance_matrix)


In [6]:
X_mmj_matrix_python_Floyd_Warshall = cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(distance_matrix)


In [7]:
print(np.allclose(X_mmj_matrix_python_algo_1, X_mmj_matrix_python_Floyd_Warshall)) 
print(np.sum(np.abs(X_mmj_matrix_python_algo_1 - X_mmj_matrix_python_Floyd_Warshall))) 


True
0.0


In [8]:
print(X_mmj_matrix_python_algo_1[:10, :10])  

[[ 0. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [25.  0. 25. 25. 25. 25. 25. 25. 27. 25.]
 [14. 14.  0. 16. 16. 15. 14. 14. 27. 20.]
 [14. 14. 13.  0. 16. 15. 14. 14. 27. 20.]
 [14. 14. 13. 16.  0. 15. 14. 14. 27. 20.]
 [31. 31. 31. 31. 31.  0. 31. 31. 31. 31.]
 [14. 14.  9. 16. 16. 15.  0.  8. 27. 20.]
 [14. 14.  9. 16. 16. 15. 14.  0. 27. 20.]
 [14.  6. 12.  6. 16. 15. 12. 12.  0. 20.]
 [14. 14. 13. 16. 16. 11. 14. 14. 27.  0.]]


In [9]:
print(X_mmj_matrix_python_Floyd_Warshall[:10, :10]) 

[[ 0. 30. 30. 30. 30. 30. 30. 30. 30. 30.]
 [25.  0. 25. 25. 25. 25. 25. 25. 27. 25.]
 [14. 14.  0. 16. 16. 15. 14. 14. 27. 20.]
 [14. 14. 13.  0. 16. 15. 14. 14. 27. 20.]
 [14. 14. 13. 16.  0. 15. 14. 14. 27. 20.]
 [31. 31. 31. 31. 31.  0. 31. 31. 31. 31.]
 [14. 14.  9. 16. 16. 15.  0.  8. 27. 20.]
 [14. 14.  9. 16. 16. 15. 14.  0. 27. 20.]
 [14.  6. 12.  6. 16. 15. 12. 12.  0. 20.]
 [14. 14. 13. 16. 16. 11. 14. 14. 27.  0.]]
