In [1]:
exec(open("./funcs/mmj_functions.py").read())

In [2]:
def cal_mmj_matrix_algo_1_python_dis_matrix(distance_matrix):
 
    N = len(distance_matrix)
   
    mmj_matrix = np.zeros((N,N))

    mmj_matrix[0,1] = distance_matrix[0,1]
    mmj_matrix[1,0] = distance_matrix[1,0]
 
    for kk in range(2,N):
        cal_n_mmj(distance_matrix, mmj_matrix, kk)
    return mmj_matrix

In [3]:
def cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(distance_matrix):
    n = len(distance_matrix)    
    p = distance_matrix.copy()
 
    for i in range(n):
        for j in range(n):
            if i != j:
                for k in range(n):
                    if i != k and j != k:
                        p[j,k] = min (p[j,k], max (p[j,i], p[i,k])) 
    return p

In [4]:
import numpy as np
import random

# create distance matrix of a directed graph

def create_distance_matrix(edges, num_nodes):
 
    dist_matrix = np.full((num_nodes, num_nodes), np.inf)
 
    np.fill_diagonal(dist_matrix, 0)
 
    for u, v, w in edges:
        dist_matrix[u, v] = w
    
    return dist_matrix

 
num_nodes = 100

edges = []
for _ in range(50000):  
    u = random.randint(0, num_nodes - 1)
    v = random.randint(0, num_nodes - 1)
    if u != v:
        w = int(random.uniform(1, 1000))
        edges.append((u, v, w))
 
distance_matrix = create_distance_matrix(edges, num_nodes)

print(distance_matrix[:10, :10])  


[[  0.   7.  55. 883. 293. 330. 296. 130. 542. 732.]
 [228.   0. 662. 362. 753. 427. 122. 471. 400. 332.]
 [468. 298.   0.  inf 844. 405. 262.  60. 467. 793.]
 [223. 426. 387.   0. 758. 678.  89. 821. 474. 821.]
 [ 48. 509. 205. 496.   0.   6. 292.  94. 955. 669.]
 [475. 664. 489. 409. 543.   0. 254. 160. 681. 442.]
 [ 58. 393. 170. 319. 709. 329.   0. 920. 308.  18.]
 [310. 690. 543. 114. 611. 859.  12.   0. 961. 191.]
 [765.  67. 282. 947. 762. 284. 411. 239.   0. 600.]
 [291. 815.   5. 134. 507. 312. 269. 647. 283.   0.]]


In [5]:

X_mmj_matrix_python_algo_1 = cal_mmj_matrix_algo_1_python_dis_matrix(distance_matrix)


In [6]:
X_mmj_matrix_python_Floyd_Warshall = cal_mmj_variant_of_Floyd_Warshall_python_dis_matrix(distance_matrix)


In [7]:
print(np.allclose(X_mmj_matrix_python_algo_1, X_mmj_matrix_python_Floyd_Warshall)) 
print(np.sum(np.abs(X_mmj_matrix_python_algo_1 - X_mmj_matrix_python_Floyd_Warshall))) 


True
0.0


In [8]:
print(X_mmj_matrix_python_algo_1[:10, :10])  

[[ 0.  7. 18. 18. 11. 11. 13. 16. 14. 18.]
 [16.  0. 18. 18. 11. 11. 13. 16. 14. 18.]
 [16.  9.  0. 18. 11. 11. 13. 16. 14. 18.]
 [23. 23. 23.  0. 23. 23. 23. 23. 23. 23.]
 [16.  9. 18. 18.  0.  6. 13. 16. 14. 18.]
 [16.  9. 18. 18. 11.  0. 13. 16. 14. 18.]
 [16. 15. 18. 18. 15. 15.  0. 16. 15. 18.]
 [16.  9. 18. 18. 11. 11. 12.  0. 14. 18.]
 [16. 13. 18. 18. 13. 13. 13. 16.  0. 18.]
 [16.  9.  5. 15. 11. 11. 13. 16. 14.  0.]]


In [9]:
print(X_mmj_matrix_python_Floyd_Warshall[:10, :10]) 

[[ 0.  7. 18. 18. 11. 11. 13. 16. 14. 18.]
 [16.  0. 18. 18. 11. 11. 13. 16. 14. 18.]
 [16.  9.  0. 18. 11. 11. 13. 16. 14. 18.]
 [23. 23. 23.  0. 23. 23. 23. 23. 23. 23.]
 [16.  9. 18. 18.  0.  6. 13. 16. 14. 18.]
 [16.  9. 18. 18. 11.  0. 13. 16. 14. 18.]
 [16. 15. 18. 18. 15. 15.  0. 16. 15. 18.]
 [16.  9. 18. 18. 11. 11. 12.  0. 14. 18.]
 [16. 13. 18. 18. 13. 13. 13. 16.  0. 18.]
 [16.  9.  5. 15. 11. 11. 13. 16. 14.  0.]]
